inherit kernel-resin

FILESEXTRAPATHS_prepend := "${THISDIR}/linux-4.17:"

# These patches were fetched from the lovely guys at armbian: https://github.com/armbian/build/tree/master/patch/kernel/sunxi-next
SRC_URI_append = "\
	file://general-0001-mfd-axp20x.patch \
	file://general-0002-mfd-axp20x.patch \
	file://general-0003-mfd-axp20x.patch \
	file://general-45-add-h3-cpu-OPP-table.patch \
	file://general-46-H3-add-opp-table-to-cpu.patch \
	file://general-a64-enable-fsl-timer-errata.patch \
	file://general-add-configfs-overlay.patch \
	file://general-add-h3-mixer1.patch \
	file://general-add-HDMI-sound-nodes-DT.patch \
	file://general-add-i2s-DT-pins.patch \
	file://general-add-nand-H27UBG8T2BTR.patch \
	file://general-add-overlay-compilation-support.patch \
	file://general-add-proc-cpuinfo-entries.patch \
	file://general-aufs4.17-20180611.patch \
	file://general-enable-allwinner-SoCs-SID-support.patch \
	file://general-enable-kernel-dtbs-symbol-generation.patch \
	file://general-h3-h5-Add-r_i2c-controller.patch \
	file://general-h3-h5-Add-r_i2c-pins.patch \
	file://general-increasing_DMA_block_memory_allocation_to_2048.patch \
	file://general-ov5640-support-5M-2542x1944-resolution.patch \
	file://general-packaging-4.17-next.patch \
	file://general-provoke-the-early-load-of-sun8i-codec.patch \
	file://general-spidev-remove-warnings.patch \
	file://general-sunxi-overlays.patch \
	file://general-sunxi-rtc-clocksource.patch \
	file://camera-add-the-H3-H5-CSI-controller.patch \
	file://camera-add-support-for-allwinner-CSI-with-tiny-fix.patch \
	file://sunxi-h5-add-gpio-regulator-overclock.patch \
	file://board-0001-orangepi-one-plus-add-device.patch \
	file://board-0002-orangepi-lite2-add-device.patch \
	file://board-47-01-enable-dvfs-opi-zero.patch \
	file://board-47-02-enable-dvfs-opi-one.patch \
	file://board-47-05-enable-dvfs-opi-lite.patch \
	file://board-add-nanopi-m1-plus2.patch \
	file://board-add-sy8106a-regulator-driver.patch \
	file://board-bpi-m2-zero-enable-dvfs.patch \
	file://board-bpi-m3-make-ethernet-working.patch \
	file://board-h3-address-some-stability-issues.patch \
	file://board-lime-a10-add-240-mhz-cpufreq.patch \
	file://board-nanopiair-h3-camera-wifi-bluetooth-otg.patch \
	file://board-nanopi-neo-core-add-emmc.patch \
	file://board-nanopi-neo-fix-random-eth-mac.patch \
	file://board-orangepi-pc2-add-spi-flash.patch \
	file://board-orangepiwin-add-lots-of-stuff.patch \
	file://board-orangepi-zero-plus2-onboard-led-support.patch \
	file://board-orangepi-zero-plus-add-regulator.patch \
	file://update-board-add-nanopi-neo-core2.patch \
	file://update-nanopi-neo2-v1.1-DT.patch \
	file://update-nanopi-neo-plus2-enable-regulator-fix-leds.patch \
	file://dvb-revert-softirq-let-ksoftirqd-do-its-job.patch \
	file://dvfs-regulator-opi-2.patch \
	file://dvfs-regulator-opi-pc2.patch \
	file://dvfs-regulator-opi-pc.patch \
	file://nand-disable-badblock-check-for-migration.patch.disabled \
	file://network-1-5-dt-bindings-allow-dwmac-sun8i-to-use-other-devices-exported-regmap.patch \
	file://network-2-5-net-stmmac-dwmac-sun8i-Use-regmap_field-for-syscon-register-access.patch \
	file://network-3-5-net-stmmac-dwmac-sun8i-Allow-getting-syscon-regmap-from-device.patch \
	file://network-4-5-drivers-soc-sunxi-export-a-regmap-for-EMAC-clock-reg-on-A64.patch \
	file://ths-21-sun4i-gpadc-iio-add-split-sun8i.patch \
	file://ths-22-sun4i-gpadc-iio-add-H3-support.patch \
	file://ths-23-sun4i-gpadc-iio-add-H3-thermal-sensor-DT.patch \
	file://ths-24-sun4i-gpadc-iio-add-H3-CPU-thermal-zone.patch \
	file://ths-25-sun4i-gpadc-iio-workaround-for-raw-0-read.patch \
	file://ths-26-sun4i-gpadc-iio-add-h5-a64-support.patch \
	file://ths-27-sun4i-gpadc-iio-add-h5-DT.patch \
	file://ths-29-sun4i-gpadc-iio-add-h5-thermal-zone.patch \
	file://wifi-brcmfmac-define-more-bits-for-the-flags-of-struct-brcmf_sta_info_le.patch \
	file://wifi-brcmfmac-update-STA-info-struct-to-the-v5.patch \
	file://wifi-brcmfmac-v4.patch \
	file://wifi-orangepi-pc-plus-pwrseq.patch \
	file://wifi-orangepi-prime.patch \
	file://wifi-orangepi-zero-fix-xradio-interrupt.patch \
	file://defconfig \
"
